version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    command: python -u app.py
    container_name: flask
    image: flask
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - './api:/api'
